apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    kerberosService: dn1
    job: kerberostest
  name: dn1
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 55555
    targetPort: 0
  selector:
    kerberosService: dn1
